In [15]:
import torch

# Creamos un tensor de ejemplo
tensor = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]],
                       [[1, 6, 3],
                       [4, 9, 6],
                       [7, 1, 9]]])

print(tensor.shape)

# Calculamos la suma a lo largo del eje 0 (columnas)
suma_eje_0 = torch.sum(tensor, dim=(0,1,2))
print("Suma a lo largo del eje 0:")
print(suma_eje_0)
#print(suma_eje_0.shape)# da un tensor de 3 elementos osea 3 columnas

# Calculamos la suma a lo largo del eje 1 (filas)
#suma_eje_1 = torch.sum(tensor, dim=(1,0))
#print("Suma a lo largo del eje 1:")
#print(suma_eje_1)
#print(suma_eje_1.shape)# da un tensor de 3 elementos osea 3 filas


torch.Size([2, 3, 3])
Suma a lo largo del eje 0:
tensor(91)


In [35]:
#tensor ejemplo (2,3)   2 filas 3 columnas

#tener 2 imagenes
tensor2 = torch.tensor([[1, 2,3],
                          [4, 5,7]])
tensor2=torch.nn.parameter.Parameter(tensor2,requires_grad=False)
#tensor ejemplo(3,3)  
# como tener 3 kernels
tensor3 = torch.tensor([[1, 2,3],
                            [4, 5,7],
                            [1, 2,3]])
tensor3=torch.nn.parameter.Parameter(tensor3,requires_grad=False)

                            




print(tensor2.unsqueeze(1).shape)
print(tensor3.unsqueeze(0).shape)

#crear tensor 2 ejemplo 3,2,2
conv = tensor2.unsqueeze(1)*tensor3.unsqueeze(0)
print(conv)

torch.Size([2, 1, 3])
torch.Size([1, 3, 3])
tensor([[[ 1,  4,  9],
         [ 4, 10, 21],
         [ 1,  4,  9]],

        [[ 4, 10, 21],
         [16, 25, 49],
         [ 4, 10, 21]]])


In [25]:
import torch
import torch.nn as nn

# Definir tu función de convolución personalizada
class MyConvolution(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size):
        super(MyConvolution, self).__init__()
        self.weight = nn.Parameter(torch.randn(out_channels, in_channels, kernel_size, kernel_size))
        self.bias = nn.Parameter(torch.zeros(out_channels))
        self.kernel_size = kernel_size

    def forward(self, x):
        batch_size, in_channels, height, width = x.size()
        out_channels = self.weight.size(0)

        # Calcular el tamaño de salida
        output_height = height - self.kernel_size + 1
        output_width = width - self.kernel_size + 1

        # Inicializar la matriz de salida
        output = torch.zeros(batch_size, out_channels, output_height, output_width)

        # Realizar la convolución
        for i in range(output_height):
            for j in range(output_width):
                receptive_field = x[:, :, i:i+self.kernel_size, j:j+self.kernel_size]
                print(receptive_field.shape)
                print(self.weight.shape)
                conv = torch.sum(receptive_field * self.weight, dim=(1, 2, 3)) + self.bias
                output[:, :, i, j] = conv

        return output

# Ejemplo de uso
input = torch.randn(1, 3, 32, 32)  # Ejemplo de tensor de entrada
conv = MyConvolution(3, 64, 3)  # Crear una instancia de tu función de convolución personalizada
output = conv(input)  # Realizar la convolución

print(output.size())  # Imprimir el tamaño de salida


torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([64, 3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.

In [29]:
import torch
import torch.nn as nn

class MyConvolution(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size):
        super(MyConvolution, self).__init__()
        self.weight = nn.Parameter(torch.randn(out_channels, in_channels, kernel_size, kernel_size))
        self.bias = nn.Parameter(torch.zeros(out_channels))
        self.kernel_size = kernel_size

    def forward(self, x):
        batch_size, in_channels, height, width = x.size()
        out_channels = self.weight.size(0)

        output_height = height - self.kernel_size + 1
        output_width = width - self.kernel_size + 1

        output = torch.zeros(batch_size, out_channels, output_height, output_width)

        # Realizar la convolución
        for i in range(output_height):
            for j in range(output_width):
                receptive_field = x[:, :, i:i+self.kernel_size, j:j+self.kernel_size]
                conv = torch.sum(receptive_field.unsqueeze(1) * self.weight.unsqueeze(0), dim=(2, 3, 4)) + self.bias.unsqueeze(0)
                print(receptive_field.unsqueeze(1).shape)
                print(self.weight.unsqueeze(0).shape)
                output[:, :, i, j] = conv.squeeze()

        return output

# Ejemplo de uso
input = torch.randn(16, 3, 32, 32)  # Ejemplo de tensor de entrada con un lote de tamaño 16
conv = MyConvolution(3, 64, 3)  # Crear una instancia de tu función de convolución personalizada
output = conv(input)  # Realizar la convolución

print(output.size())  # Imprimir el tamaño de salida


torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([1, 64, 3, 3, 3])
torch.Size([16

In [38]:
import torch

# Creamos dos tensores de ejemplo
tensor1 = torch.tensor([[[1, 2, 3]],
                        [[4, 5, 6]]])

print(tensor1.shape)

tensor2 = torch.tensor([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]]])

print(tensor2.shape)

# Realizamos una suma entre los tensores
suma = tensor1 + tensor2
print(suma)


torch.Size([2, 1, 3])
torch.Size([1, 3, 3])
tensor([[[ 2,  4,  6],
         [ 5,  7,  9],
         [ 8, 10, 12]],

        [[ 5,  7,  9],
         [ 8, 10, 12],
         [11, 13, 15]]])


In [41]:
input = torch.randn(1, 1, 5, 5)  # Ejemplo de tensor de entrada con un lote de tamaño 16
print(input)

tensor([[[[-0.7450, -0.1985,  1.5039,  0.0297, -0.3528],
          [-0.8572,  0.2318, -2.3545,  0.1412, -0.1344],
          [ 0.7599,  0.4255, -0.9361, -0.3726,  0.9766],
          [ 0.6650, -0.2268, -0.9676, -0.5582,  0.6879],
          [-0.9037, -0.7848,  0.3062,  1.5373,  2.2183]]]])


In [43]:
salida=torch.nn.functional.max_pool2d(input, kernel_size=2,padding=1)
print(salida.shape)
print(salida)

torch.Size([1, 1, 3, 3])
tensor([[[[-0.7450,  1.5039,  0.0297],
          [ 0.7599,  0.4255,  0.9766],
          [ 0.6650,  0.3062,  2.2183]]]])
